### PR TITLE
WL-3705 Basic LTI tool pop-option works correctly.

### PR DESCRIPTION
**Pull request by ouit0408**
Checking for the 'Always add pop-option' in the content and tool and
setting accordingly in the 'contentModel'.

### CODE REVIEW

**Comment by buckett** [comment]
It seems that other properties use `org.sakaiproject.lti.impl.BaseLTIService#filterContent` to make sure that a tool gets the correct property. This supports the popup value, so could it not be that this method isn't getting called when it should be?

**Comment by buckett** [comment]
Did you get any reply back about this being the right way to fix it?

**Comment by ouit0408** [comment]
I emailed Dr Chuck and he referred me to Stephen P Vickers(from SPV Software Products) who in turn passed the mail to Dr Chuck saying that it is a sakai related issue . No replies from Dr Chuck yet.Shall I buzz him again?

**Comment by buckett** [comment]
Did anyone have any comments about this?

**Comment by ouit0408** [comment]
No comments yet.

**Comment by buckett** [comment]
#13 looks to be a slightly more complete fix so closing in preference to that one for now.

**Pull request closed without merging**
